#!/bin/zsh

set -eu

typeset -i full_memory_kib=0
typeset -i available_memory_kib=0

while read -r key value unit; do
    case "$key" in
        MemTotal:)
            full_memory_kib=$value
            ;;
        MemAvailable:)
            available_memory_kib=$value
            ;;
    esac

    if (( full_memory_kib > 0 && available_memory_kib > 0 )); then
        break
    fi
done < /proc/meminfo

if (( full_memory_kib == 0 || available_memory_kib == 0 )); then
    jq -n --compact-output \
        --arg text "  N/A" \
        --arg class "red" \
        '{ text: $text, class: $class }'
    exit 0
fi

typeset -i using_memory_kib=$((full_memory_kib - available_memory_kib))
typeset -i use_rate_x100=$((10000 * using_memory_kib / full_memory_kib))
typeset -i block_num=$(((use_rate_x100 + 999) / 1000))
typeset -i space_num

(( block_num < 1 )) && block_num=1
(( block_num > 10 )) && block_num=10
space_num=$((10 - block_num))

using_memory_readable=$(numfmt --from-unit=1024 --to=iec "$using_memory_kib")
full_memory_readable=$(numfmt --from-unit=1024 --to=iec "$full_memory_kib")
use_rate=$(printf '%d.%02d' $((use_rate_x100 / 100)) $((use_rate_x100 % 100)))

blocks=""
for (( i = 0; i < block_num; i++ )); do
    blocks+="█"
done

spaces=""
for (( i = 0; i < space_num; i++ )); do
    spaces+=" "
done

bar="${blocks}${spaces}"

class=""
case "${block_num}" in
    <1-2>  ) class="" ;;
    <3-4>  ) class="green" ;;
    <5-6>  ) class="yellow" ;;
    <7-8>  ) class="orange" ;;
    <->    ) class="red" ;;
esac

full_text=$(printf '  %s / %s [%s]  %s%%' \
    "$using_memory_readable" \
    "$full_memory_readable" \
    "$bar" \
    "$use_rate")

jq -n --compact-output   \
    --arg ft "$full_text"   \
    --arg color "$class"    \
    '{ text: $ft, class: $color }'
