#!/bin/zsh

readonly FREE_MEM_ROW=$(free --bytes|grep Mem)

readonly FULL_MEMORY=$(echo ${FREE_MEM_ROW}|awk '{print $2}')
readonly AVAILABLE_MEMORY=$(echo ${FREE_MEM_ROW}|awk '{print $7}')

readonly USING_MEMORY=$(echo "${FULL_MEMORY}-${AVAILABLE_MEMORY}"|bc)

readonly USING_MEMORY_READABLE=$(echo "${USING_MEMORY}"|numfmt --to=iec)
readonly FULL_MEMORY_READABLE=$(echo "${FULL_MEMORY}"|numfmt --to=iec)

readonly USE_RATE=$(echo "scale=2; 100*${USING_MEMORY}/${FULL_MEMORY}"|bc -l)
readonly BLOCK_NUM=$(echo "scale=0; ${USE_RATE}/10+1"|bc)
readonly SPACE_NUM=$(echo "10-${BLOCK_NUM}"|bc)

readonly BLOCKS=$(printf '█%.0s' $(seq "${BLOCK_NUM}"))
readonly SPACES=$(printf ' %.0s' $(seq "${SPACE_NUM}"))

readonly BAR="${BLOCKS}${SPACES}"

class=""
case "${BLOCK_NUM}" in
    <1-2>  ) class="" ;;
    <3-4>  ) class="green" ;;
    <5-6>  ) class="yellow" ;;
    <7-8>  ) class="orange" ;;
    <->    ) class="red" ;;
esac

readonly FULL_TEXT=$(printf '  %s / %s [%s]  %s%%' \
    "$USING_MEMORY_READABLE" \
    "$FULL_MEMORY_READABLE" \
    "$BAR" \
    "$USE_RATE")

jq -n --compact-output   \
    --arg ft "$FULL_TEXT"   \
    --arg color "$class"    \
    '{ text: $ft, class: $color }'
