#!/bin/zsh

set -e

readonly SCRIPT_NAME="$(basename "${BASH_SOURCE:-$0}")"

usage () {
    cat << EOS
Usage: $SCRIPT_NAME
       $SCRIPT_NAME <command>
Update portage, kernel, and non-systemwide packages (pip, gem etc.). If no command is specified, then these all will be updated.
Run this script as NON-ROOT. Root user cannot update non-systemwide packages (pip, gem etc.).

Available commands:
    non_systemwide  Update non-systemwide packages (pip, gem etc.) only.
    help            Show this help.
EOS
}

# pip will exit with return status non-zero when there is no package to update.
# Therefore only try to update when outdated exists.
update_pip () {
    if ! command -v pip >/dev/null 2>&1; then
        return
    fi

    local package_list
    package_list="$(pip list --outdated --format=freeze | grep -v 'notice' | awk -F '=' '{print $1}')"

    if [[ -n $package_list ]]; then
        printf '%s\n' "$package_list" | xargs -n1 pip install --upgrade --user
    fi
}

non_systemwide () {
    command_exists () {
        command -v $1 > /dev/null
    }

    update_pip
    command_exists gem && gem update
    command_exists rustup && rustup update

    cabal update

    ghcup upgrade
    ghcup install ghc
    ghcup install cabal
    ghcup install hls
    ghcup install stack

    command_exists opam && opam update
}


if [[ $(whoami) = "root" ]]; then
    echo "Run as non-root. Root user can't update non-systemwide packages such as pip, gem, etc." >&2
    exit 1
fi

if [[ $# -gt 1 ]]; then
    usage >&2
    exit 1
fi

case "$1" in
    "" )
        readonly DISTRIBUTION=$(cat /etc/*-release|grep '^ID'|awk -F '[=]' '{print $2}')

        if [[ $DISTRIBUTION == gentoo ]]; then
            sudo ./update_gentoo.sh
        fi

        non_systemwide ;;
    "non_systemwide") non_systemwide ;;
    "help") usage ;;
    * ) usage >&2 && exit 1 ;;
esac
